"""updating Mid to Mid-Level in db

Revision ID: 1536865ea0f7
Revises: bc5c2a76e30d
Create Date: 2026-02-05 08:02:59.079890

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "1536865ea0f7"
down_revision = "bc5c2a76e30d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.execute(
        """
        UPDATE jobs_table
        SET experience_level = 'Mid-Level'
        WHERE experience_level = 'Mid'
        """
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    """
    UPDATE jobs_table
    SET experience_level = 'Mid'
    WHERE experience_level = 'Mid-Level'
    """
