"""adding_initial_tables

Revision ID: bc5c2a76e30d
Revises:
Create Date: 2026-01-22 04:40:14.228994

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "bc5c2a76e30d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "jobs_table",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("title", sa.String(length=128), nullable=False),
        sa.Column("source", sa.String(length=128), nullable=False),
        sa.Column("source_id", sa.String(length=128), nullable=True),
        sa.Column("company_name", sa.String(length=128), nullable=False),
        sa.Column("experience_level", sa.String(length=128), nullable=False),
        sa.Column("url", sa.Text(), nullable=True),
        sa.Column("salary", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("location", sa.String(length=128), nullable=True),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_id"),
    )
    op.create_table(
        "test_table",
        sa.Column("test_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("test_name", sa.String(length=128), nullable=False),
        sa.Column(
            "create_time",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("test_id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("test_table")
    op.drop_table("jobs_table")
    # ### end Alembic commands ###
