"""adding_initial_tables

Revision ID: 84f0059a59d3
Revises: 
Create Date: 2026-01-21 03:58:47.622728

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84f0059a59d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobs_table',
    sa.Column('id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('source', sa.String(length=128), nullable=False),
    sa.Column('company_name', sa.String(length=128), nullable=False),
    sa.Column('employment_type', sa.String(length=128), nullable=False),
    sa.Column('experience_level', sa.String(length=128), nullable=False),
    sa.Column('url', sa.String(length=128), nullable=True),
    sa.Column('salary', sa.String(length=128), nullable=True),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('test_table',
    sa.Column('test_id', sa.Uuid(as_uuid=False), nullable=False),
    sa.Column('test_name', sa.String(length=128), nullable=False),
    sa.Column('create_time', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('test_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_table')
    op.drop_table('jobs_table')
    # ### end Alembic commands ###
